/**
 * Generated by openapi-tanstack-query-solid v1.0.2 🍺
 * Do not edit manually.
 * Swagger Petstore
 * OpenAPI spec version: 1.0.0
 */
import type { DachshundBreed } from './dachshundBreed';

export interface Dachshund {
  breed: DachshundBreed;
  length: number;
}
